version: "3.3"

services:
  front:
    image: node:alpine
    volumes:
      - .:/core
    working_dir: /core
    entrypoint:
      - /bin/sh
      - -c
    command:
      - yarn start
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:3000
