name: Review assigning

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
  pull_request_review:

jobs:
  reviews:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set reviewers or merge
        uses: KaMeHb-UA/auto-review-action@master
        with:
          type: distributed
          scheme-file: review-scheme.yml
          token: ${{ secrets.GITHUB_TOKEN }}
